# Generated by Django 5.0.4 on 2024-09-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_events_category_alter_events_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='test',
        ),
    ]
