# Generated by Django 5.0.4 on 2024-09-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_events_rsvp_deadline_events_capacity_events_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('unlisted', 'Unlisted'), ('concert', 'Concert'), ('book_club', 'Book club'), ('potluck', 'Potluck'), ('meeting', 'Meeting')], default='unlisted', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
    ]
